apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxapp1-ingress-service
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        defaultBackend:
          service:
            name: usermgmt-webapp-service
            port:
              number: 80
