apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-state
spec:
  storageClassName: statestorage
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
